install:
  - ps: Install-Product node Current x64
  - npm install -g npm@4 --silent
  - npm install -g vsce
  - npm install

build_script:
  - npm run coverage:disable
  - vsce package
  
test_script:
  - npm run testonly

artifacts:
  - path: "*.vsix"
