
language: node_js
dist: trusty

os:
  - osx
  - linux
  - windows

node_js:
  - "10"

addons:
  sonarcloud:
    organization: "prb28-github"

before_install:
  - npm install -g npm@latest
  - if [ $TRAVIS_OS_NAME == "linux" ];
    then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - if [ $TRAVIS_OS_NAME == "linux" ];
    then
      npm run test:coverage;
      node_modules/.bin/coveralls < coverage/lcov.info;
      npm run tslint;
      sonar-scanner;
    else
      npm run test;
    fi
