trigger:
  branches:
    include:
      - master
  #tags:
  #  include:
  #  - v*

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    linux-package:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - task: SonarQubePrepare@4
    condition: and(succeeded(), eq(variables['Agent.Name'], 'linux'))
    inputs:
      SonarQube: 'Sonar'
      scannerMode: 'CLI'
      configMode: 'file'

  - task: Npm@1
    inputs:
      command: 'install'

  - bash: |
      echo ">>> Package"
      npm run coverage:disable
      vsce package
    displayName: Package
    condition: and(succeeded(), eq(variables['Agent.Name'], 'linux-package'))

  - bash: |
      echo ">>> Compile vscode-test"
      npm run vscode:prepublish
      npm run test:coverage
      npm run tslint
    displayName: Run Tests
    condition: and(succeeded(), ne(variables['Agent.Name'], 'linux-package'))
    env:
      DISPLAY: ":99.0"

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: "out/**/test-results.xml"
    condition: and(succeededOrFailed(), eq(variables['Agent.Name'], 'linux'))

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"
    condition: and(succeeded(), eq(variables['Agent.Name'], 'linux'))

  - bash: |
      echo ">>> Publish to coveralls"
      node_modules/.bin/coveralls < coverage/lcov.info
    displayName: Publish to Coveralls
    condition: and(succeeded(), eq(variables['Agent.Name'], 'linux'))

  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), ne(variables['Agent.Name'], 'linux-package'))
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '*.vsix'
      publishLocation: 'Container'
    env:
      DISPLAY: ":99.0"

  - task: SonarQubeAnalyze@4
    condition: and(succeeded(), eq(variables['Agent.Name'], 'linux'))

  - task: SonarQubePublish@4
    condition: and(succeeded(), eq(variables['Agent.Name'], 'linux'))
