trigger:
  branches:
    include:
      - master
  #tags:
  #  include:
  #  - v*

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - bash: |
      echo ">>> Compile vscode-test"
      npm install
      npm run vscode:prepublish
      npm run test:coverage
    displayName: Run Tests
    env:
      DISPLAY: ":99.0"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: "out/**/test-results.xml"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"

  - bash: |
      echo ">>> Publish to coveralls"
      node_modules/.bin/coveralls < coverage/lcov.info
    displayName: Publish to Coveralls
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
    displayName: "Prepare analysis on SonarCloud"
    inputs:
      SonarCloud: "SonarCloud-CodeAnalysis-Server"
      organization: prb28
      projectKey: "prb28_vscode-amiga-assembly"
      projectName: "VSCode Amiga Assembly"
      extraProperties: |
        sonar.language=typescript
        sonar.sources=src
        sonar.tests=src
        sonar.sourceEncoding=UTF-8
        sonar.exclusions=src/mathcalc.js
        #sonar.test.exclusions=src/tests/*
        sonar.testExecutionReportPaths=out/test-report.xml
        sonar.coverage.exclusions=src/test/*.ts,src/*.js
        sonar.test.inclusions=src/test/*.ts
        sonar.typescript.file.suffixes=.ts,.tsx
        sonar.typescript.lcov.reportPaths=coverage/lcov.info
        sonar.typescript.tslint.reportPaths=tslint-report.json
        sonar.branch.name=$(Build.SourceBranchName)
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
  - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
    displayName: "Run Code Analysis"
    continueOnError: false
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
  - task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
    displayName: "Publish Quality Gate Result"
    continueOnError: false
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
